import { ListingRow, CategoryRow, ListingImageRow } from "@/lib/supabase/types";

export interface MarketplaceListingItem extends ListingRow {
  category?: CategoryRow | null;
  listing_images?: (ListingImageRow & { url?: string })[];
}

export const MOCK_LISTINGS: MarketplaceListingItem[] = [
  // ── Cars ──
  {
    id: "lst-car-tesla-3",
    owner_id: "user_owner_01",
    category_id: "cat-cars",
    title: "Tesla Model 3 Long Range AWD (2024)",
    description: "Dual motor all-wheel drive, premium audio, Autopilot, 340+ mile real-world range. Clean, fully charged on handover.",
    price_per_day: 85,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80"],
    location: "Metro Downtown • Free pickup",
    attributes: {
      make: "Tesla",
      model: "Model 3",
      year: 2024,
      transmission: "Automatic",
      fuel_type: "Electric",
      security_deposit: 250,
      seats: 5,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-cars",
      name: "Cars",
      slug: "cars",
      icon: "Car",
      description: "Sedans, SUVs, electric vehicles & light commercial trucks",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-car-1",
        listing_id: "lst-car-tesla-3",
        image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "lst-car-ford-f150",
    owner_id: "user_owner_02",
    category_id: "cat-cars",
    title: "Ford F-150 Lightning Lariat 4x4",
    description: "All-electric full-size pickup with 9.6kW Pro Power Onboard generator capabilities, extended range battery and towing package.",
    price_per_day: 130,
    images: ["https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80"],
    location: "Industrial District • Delivery available",
    attributes: {
      make: "Ford",
      model: "F-150 Lightning",
      year: 2023,
      transmission: "Automatic",
      fuel_type: "Electric",
      security_deposit: 400,
      payload_lbs: 2235,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-cars",
      name: "Cars",
      slug: "cars",
      icon: "Car",
      description: "Sedans, SUVs, electric vehicles & light commercial trucks",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-car-2",
        listing_id: "lst-car-ford-f150",
        image_url: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Heavy Equipment ──
  {
    id: "lst-he-cat-320",
    owner_id: "user_owner_03",
    category_id: "cat-heavy-equipment",
    title: "Caterpillar 320 GC Hydraulic Excavator",
    description: "20.5-tonne crawler excavator optimized for high-volume trenching, site bulk earthworks and utility installation.",
    price_per_day: 450,
    images: ["https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1200&q=80"],
    location: "Heavy Fleet Depot • Transport required",
    attributes: {
      operating_weight: "20,500 kg",
      power_source: "Diesel",
      max_reach: "9.87 m",
      bucket_capacity: "1.19 m³",
      security_deposit: 1500,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-heavy-equipment",
      name: "Heavy Equipment",
      slug: "heavy-equipment",
      icon: "HardHat",
      description: "Excavators, bulldozers, cranes & earthmovers for construction",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-he-1",
        listing_id: "lst-he-cat-320",
        image_url: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "lst-he-cat-d6",
    owner_id: "user_owner_03",
    category_id: "cat-heavy-equipment",
    title: "CAT D6T XL Track-Type Bulldozer",
    description: "Engineered for precision earth clearing, heavy site grading, and bulk leveling with VPAT blade and Cat Grade with 3D.",
    price_per_day: 520,
    images: ["https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=1200&q=80"],
    location: "Logistics Hub North • Transport required",
    attributes: {
      operating_weight: "21,300 kg",
      power_source: "Diesel",
      max_reach: "N/A - Blade Width 3.88m",
      security_deposit: 1800,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-heavy-equipment",
      name: "Heavy Equipment",
      slug: "heavy-equipment",
      icon: "HardHat",
      description: "Excavators, bulldozers, cranes & earthmovers for construction",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-he-2",
        listing_id: "lst-he-cat-d6",
        image_url: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Boats ──
  {
    id: "lst-boat-sea-ray",
    owner_id: "user_owner_04",
    category_id: "cat-boats",
    title: "Sea Ray Sundancer 320 Sports Cruiser",
    description: "Twin MerCruiser 350HP engines, bow lounge, air-conditioned cabin, wet bar, and Garmin navigation. Perfect for harbor & offshore rentals.",
    price_per_day: 750,
    images: ["https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80"],
    location: "Marina North Dock • Marina pickup",
    attributes: {
      length_ft: 32,
      passenger_capacity: 10,
      captain_included: true,
      fuel_type: "Gasoline",
      security_deposit: 1000,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-boats",
      name: "Boats",
      slug: "boats",
      icon: "Ship",
      description: "Motor yachts, speedboats, pontoons & commercial tenders",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-boat-1",
        listing_id: "lst-boat-sea-ray",
        image_url: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Generators ──
  {
    id: "lst-gen-cummins-50",
    owner_id: "user_owner_05",
    category_id: "cat-generators",
    title: "Cummins 50 kVA Silent Diesel Generator Set",
    description: "Acoustically insulated canopy with 65 dBA noise level, auto-transfer switch compatible, continuous power rating with 24-hour base tank.",
    price_per_day: 160,
    images: ["https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80"],
    location: "Central Power Yard • Delivery & setup available",
    attributes: {
      power_output: "50 kVA / 40 kW",
      fuel_type: "Diesel",
      noise_level: "65 dBA @ 7m",
      phase: "Three Phase (400/230V)",
      security_deposit: 500,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-generators",
      name: "Generators",
      slug: "generators",
      icon: "Zap",
      description: "High-capacity standby diesel generators & portable silent sets",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-gen-1",
        listing_id: "lst-gen-cummins-50",
        image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Cameras ──
  {
    id: "lst-cam-sony-fx3",
    owner_id: "user_owner_06",
    category_id: "cat-cameras",
    title: "Sony FX3 Cinema Line Full-Frame Kit",
    description: "Includes cage, XLR top handle, 2x 160GB CFexpress Type A cards, 4x NP-FZ100 batteries, and Sony 24-70mm f/2.8 GM II lens.",
    price_per_day: 140,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80"],
    location: "Arts District • In-store or courier",
    attributes: {
      sensor_size: "Full Frame",
      lens_mount: "Sony E-mount",
      max_resolution: "4K 120p",
      included_lens: "Sony FE 24-70mm f/2.8 GM II",
      security_deposit: 600,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-cameras",
      name: "Cameras",
      slug: "cameras",
      icon: "Camera",
      description: "Cinema cameras, high-res mirrorless, cine lenses & lighting rigs",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-cam-1",
        listing_id: "lst-cam-sony-fx3",
        image_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Phones ──
  {
    id: "lst-phone-iphone-16",
    owner_id: "user_owner_07",
    category_id: "cat-phones",
    title: "Apple iPhone 16 Pro Max 512GB (Titanium)",
    description: "Unlocked flagship device configured for international roaming and production shoots. Includes rugged MagSafe case and 4K ProRes capture kit.",
    price_per_day: 35,
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80"],
    location: "Tech Hub Station • Instant pickup",
    attributes: {
      brand: "Apple",
      model: "iPhone 16 Pro Max",
      storage: "512GB",
      os: "iOS",
      security_deposit: 300,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-phones",
      name: "Phones",
      slug: "phones",
      icon: "Smartphone",
      description: "Flagship smartphones, satellite handsets & enterprise mobile kits",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-phone-1",
        listing_id: "lst-phone-iphone-16",
        image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Buses ──
  {
    id: "lst-bus-sprinter",
    owner_id: "user_owner_08",
    category_id: "cat-buses",
    title: "Mercedes-Benz Sprinter 15-Passenger Luxury Shuttle",
    description: "High-roof extended passenger van with reclining leather captain chairs, dual-zone AC, overhead luggage racks, and Wi-Fi hotspot.",
    price_per_day: 280,
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80"],
    location: "Airport Corridor • Chauffeur or self-drive",
    attributes: {
      passenger_capacity: 15,
      driver_provided: true,
      ac_equipped: true,
      fuel_type: "Diesel",
      security_deposit: 800,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-buses",
      name: "Buses",
      slug: "buses",
      icon: "Bus",
      description: "Passenger shuttles, charter coaches & group transit vans",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-bus-1",
        listing_id: "lst-bus-sprinter",
        image_url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },

  // ── Motorcycles ──
  {
    id: "lst-moto-bmw-1250",
    owner_id: "user_owner_09",
    category_id: "cat-motorcycles",
    title: "BMW R 1250 GS Adventure Touring",
    description: "1254cc Boxer engine with ShiftCam, aluminum panniers, Dynamic ESA, riding modes Pro, and heated grips. Road-trip ready.",
    price_per_day: 110,
    images: ["https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80"],
    location: "City Moto Center • Gear available",
    attributes: {
      engine_cc: 1254,
      helmet_included: true,
      fuel_type: "Gasoline",
      transmission: "Manual",
      security_deposit: 500,
    },
    status: "available",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: "cat-motorcycles",
      name: "Motorcycles",
      slug: "motorcycles",
      icon: "Bike",
      description: "Street cruisers, sport bikes, delivery scooters & dirt bikes",
      attribute_schema: [],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    listing_images: [
      {
        id: "img-moto-1",
        listing_id: "lst-moto-bmw-1250",
        image_url: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80",
        url: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
  },
];

export interface MockBookingItem {
  id: string;
  listing_id: string;
  renter_id: string;
  start_date: string;
  end_date: string;
  total_price: number;
  status: "pending" | "accepted" | "paid" | "active" | "returned" | "completed" | "cancelled";
  created_at: string;
}

export const MOCK_BOOKINGS: MockBookingItem[] = [
  {
    id: "bk-mock-tesla-1",
    listing_id: "lst-car-tesla-3",
    renter_id: "user_renter_99",
    start_date: "2026-10-10",
    end_date: "2026-10-14",
    total_price: 340,
    status: "accepted",
    created_at: new Date().toISOString(),
  },
  {
    id: "bk-mock-cat-1",
    listing_id: "lst-he-cat-320",
    renter_id: "user_renter_98",
    start_date: "2026-10-15",
    end_date: "2026-10-20",
    total_price: 2700,
    status: "paid",
    created_at: new Date().toISOString(),
  },
  {
    id: "bk-mock-boat-1",
    listing_id: "lst-boat-sea-ray",
    renter_id: "user_renter_97",
    start_date: "2026-10-08",
    end_date: "2026-10-11",
    total_price: 2250,
    status: "active",
    created_at: new Date().toISOString(),
  },
];
