import { EquipmentItem, EquipmentCategory, HowItWorksStep, BenefitItem } from "./types";

export const EQUIPMENT_CATEGORIES: EquipmentCategory[] = [
  {
    id: "excavators",
    name: "Excavators",
    description: "Hydraulic crawler and wheeled excavators for deep excavation, foundation trenches, and bulk earthmoving.",
    iconName: "Truck",
    machineCount: 14,
  },
  {
    id: "backhoes",
    name: "Backhoe Loaders",
    description: "Versatile dual-action machines for trenching, loading, backfilling, and utility installations.",
    iconName: "Wrench",
    machineCount: 8,
  },
  {
    id: "bulldozers",
    name: "Bulldozers",
    description: "Heavy track-type tractors engineered for land clearing, bulk earth pushing, and precision grade finishing.",
    iconName: "HardHat",
    machineCount: 11,
  },
  {
    id: "wheel-loaders",
    name: "Wheel Loaders",
    description: "High-capacity front-end articulation loaders for aggregate handling, stockpiling, and truck loading.",
    iconName: "Boxes",
    machineCount: 9,
  },
  {
    id: "cranes",
    name: "Cranes",
    description: "Rough-terrain and all-terrain telescopic boom cranes for heavy industrial hoisting and structural erection.",
    iconName: "Compass",
    machineCount: 6,
  },
  {
    id: "forklifts",
    name: "Forklifts",
    description: "High-capacity industrial and rough-terrain telehandlers and forklifts for material placement and yard operations.",
    iconName: "Layers",
    machineCount: 12,
  },
  {
    id: "dump-trucks",
    name: "Dump Trucks",
    description: "Articulated and rigid off-highway haul trucks for bulk quarry transport and site spoil removal.",
    iconName: "Truck",
    machineCount: 16,
  },
  {
    id: "road-rollers",
    name: "Road Rollers",
    description: "Single and tandem vibratory drum rollers for soil stabilization, aggregate base compaction, and asphalt paving.",
    iconName: "Cog",
    machineCount: 7,
  },
];

export const FEATURED_EQUIPMENT: EquipmentItem[] = [
  {
    id: "eq-cat-336",
    name: "CAT 336 Hydraulic Excavator",
    model: "CAT 336-07 Next Gen",
    category: "Excavators",
    categoryId: "excavators",
    image: "/images/equipment_excavator.jpg",
    description: "Tier 4 Final crawler excavator with integrated 2D grade assist, high ambient cooling, and reinforced heavy-duty boom for continuous quarry and foundation work.",
    operatingWeight: "37,200 kg",
    powerSource: "234 kW (314 HP) Diesel",
    specs: [
      { label: "Operating Weight", value: "37,200 kg" },
      { label: "Net Power", value: "234 kW / 314 HP" },
      { label: "Max Dig Depth", value: "7.52 m" },
      { label: "Bucket Capacity", value: "2.28 m³" },
    ],
    rate: {
      daily: 1250,
      weekly: 6250,
      unit: "PHP",
    },
    availability: "Available",
    suitableProjects: ["Deep Foundation Trenching", "Civil Infrastructure", "Mass Earth Excavation"],
  },
  {
    id: "eq-cat-982m",
    name: "CAT 982M High-Lift Wheel Loader",
    model: "CAT 982M Series III",
    category: "Wheel Loaders",
    categoryId: "wheel-loaders",
    image: "/images/equipment_loader.jpg",
    description: "Heavy-duty wheel loader optimized for high-volume truck loading, quarry aggregate handling, and bank-loading operations with quick-cycle transmission.",
    operatingWeight: "35,500 kg",
    powerSource: "318 kW (426 HP) Diesel",
    specs: [
      { label: "Operating Weight", value: "35,500 kg" },
      { label: "Net Power", value: "318 kW / 426 HP" },
      { label: "Bucket Capacity", value: "5.4 m³" },
      { label: "Dump Clearance", value: "3.72 m" },
    ],
    rate: {
      daily: 1100,
      weekly: 5500,
      unit: "PHP",
    },
    availability: "Available",
    suitableProjects: ["Quarry Operations", "Aggregate Hauling", "Bulk Loading Facilities"],
  },
  {
    id: "eq-cat-d11",
    name: "CAT D11 Heavy Track Bulldozer",
    model: "CAT D11T Heavy Dozer",
    category: "Bulldozers",
    categoryId: "bulldozers",
    image: "/images/equipment_dozer.jpg",
    description: "Flagship heavy track bulldozer equipped with severe-service semi-U blade, dual-shank hydraulic ripper, and automated blade stabilization for high-volume ripping.",
    operatingWeight: "104,236 kg",
    powerSource: "634 kW (850 HP) Diesel",
    specs: [
      { label: "Operating Weight", value: "104,236 kg" },
      { label: "Net Power", value: "634 kW / 850 HP" },
      { label: "Blade Capacity", value: "27.2 m³" },
      { label: "Ripper Type", value: "Dual Shank Hydraulic" },
    ],
    rate: {
      daily: 2200,
      weekly: 11000,
      unit: "PHP",
    },
    availability: "Available",
    suitableProjects: ["Mine Reclamation", "Mass Land Clearing", "Highway Grade Construction"],
  },
  {
    id: "eq-jcb-3cx",
    name: "JCB 3CX Eco Backhoe Loader",
    model: "JCB 3CX Plus Eco",
    category: "Backhoe Loaders",
    categoryId: "backhoes",
    image: "/images/equipment_backhoe.jpg",
    description: "High-mobility four-wheel drive backhoe loader with front loader bucket, side-shift extending dipper rear boom, and low-emissions fuel-efficient powertrain.",
    operatingWeight: "8,135 kg",
    powerSource: "81 kW (109 HP) Turbo Diesel",
    specs: [
      { label: "Operating Weight", value: "8,135 kg" },
      { label: "Net Power", value: "81 kW / 109 HP" },
      { label: "Max Dig Depth", value: "5.46 m (Extending)" },
      { label: "Loader Bucket", value: "1.0 m³" },
    ],
    rate: {
      daily: 650,
      weekly: 3250,
      unit: "PHP",
    },
    availability: "Available",
    suitableProjects: ["Utility Line Installation", "Urban Infrastructure", "Site Prep & Backfilling"],
  },
  {
    id: "eq-grove-rt9150e",
    name: "Grove RT9150E Rough-Terrain Crane",
    model: "Grove RT9150E Hydro",
    category: "Cranes",
    categoryId: "cranes",
    image: "/images/equipment_crane.jpg",
    description: "High-tonnage rough-terrain hydraulic mobile crane with 6-section megaform boom, inverted outrigger jacks, and multi-mode 4-wheel steering for rugged jobsites.",
    operatingWeight: "89,500 kg",
    powerSource: "261 kW (350 HP) Cummins Diesel",
    specs: [
      { label: "Max Lift Capacity", value: "135 metric tons" },
      { label: "Max Main Boom", value: "60.0 m" },
      { label: "Max Tip Height", value: "95.0 m" },
      { label: "Outrigger Stance", value: "8.5 m x 8.5 m" },
    ],
    rate: {
      daily: 2400,
      weekly: 12000,
      unit: "PHP",
    },
    availability: "Reserved",
    suitableProjects: ["Steel Erection", "Industrial Plant Assembly", "Heavy Modular Hoisting"],
  },
  {
    id: "eq-cat-cs12",
    name: "CAT CS12 GC Vibratory Compactor",
    model: "CAT CS12 GC Smooth Drum",
    category: "Road Rollers",
    categoryId: "road-rollers",
    image: "/images/equipment_roller.jpg",
    description: "High-performance single-drum soil compactor featuring dual amplitude vibration, high static linear load, and pod-style eccentric weight systems for consistent compaction.",
    operatingWeight: "12,300 kg",
    powerSource: "90 kW (121 HP) Diesel",
    specs: [
      { label: "Operating Weight", value: "12,300 kg" },
      { label: "Drum Width", value: "2,134 mm" },
      { label: "Static Linear Load", value: "33.5 kg/cm" },
      { label: "Centrifugal Force", value: "250 kN" },
    ],
    rate: {
      daily: 580,
      weekly: 2900,
      unit: "PHP",
    },
    availability: "Available",
    suitableProjects: ["Highway Sub-base Compaction", "Commercial Pad Prep", "Runway Subgrade"],
  },
];

export const HOW_IT_WORKS_STEPS: HowItWorksStep[] = [
  {
    step: "01",
    title: "Browse & Select Equipment",
    description: "Explore verified technical specifications, machine capacities, and live schedule calendars across all fleet units.",
    detail: "Filter by machine weight, digging depth, or power requirements to ensure exact project fit.",
    iconName: "Search",
  },
  {
    step: "02",
    title: "Specify Rental Schedule",
    description: "Choose your start and completion dates, job site coordinates, and delivery preferences.",
    detail: "Select site drop-off delivery or yard pickup with flexible daily, weekly, or monthly duration terms.",
    iconName: "Calendar",
  },
  {
    step: "03",
    title: "Submit & Verify Request",
    description: "Provide company and site details to receive an itemized quote with transparent rate breakdown and terms.",
    detail: "No hidden charges: clear rates for mobilization, base daily hire, and security deposit details.",
    iconName: "FileCheck",
  },
  {
    step: "04",
    title: "Dispatch & Site Handover",
    description: "Pre-inspected machinery is dispatched with full mechanical verification and operational documentation.",
    detail: "On-site walkaround inspection conducted with site supervisor before handoff.",
    iconName: "Truck",
  },
];

export const WHY_CHOOSE_BENEFITS: BenefitItem[] = [
  {
    title: "Complete Equipment Specs",
    description: "Access verified machine weight, hydraulic capacity, engine output, and dimensional limits to match project specifications accurately.",
    tag: "Verified Fleet",
    iconName: "FileText",
  },
  {
    title: "Transparent Pricing Breakdown",
    description: "Clear daily, weekly, and monthly rates with upfront transport estimates, fuel guidelines, and security deposit rules without unexpected fees.",
    tag: "Fair Rates",
    iconName: "Banknote",
  },
  {
    title: "Documented Availability",
    description: "Real-time visibility into machine deployment windows ensures reliable scheduling for project milestones and subcontractor mobilization.",
    tag: "Operational Certainty",
    iconName: "Clock",
  },
  {
    title: "Multi-Point Pre-Dispatch Inspections",
    description: "Every machine undergoes certified hydraulic, structural, and powertrain inspection prior to departure to maximize uptime on site.",
    tag: "Safety & Reliability",
    iconName: "ShieldCheck",
  },
  {
    title: "Heavy-Haul Logistics Coordination",
    description: "Dedicated transport coordination ensures timely site drop-off, heavy permitting compliance, and scheduled yard returns.",
    tag: "Site Delivery",
    iconName: "Truck",
  },
  {
    title: "Structured Commercial Workflows",
    description: "Digital rental requests, clear approval milestones, and prompt inspection handovers tailored for civil contractors and plant managers.",
    tag: "Commercial Standard",
    iconName: "SlidersHorizontal",
  },
];
